config/routes.rb
Rails.application.routes.draw do
  root :to => "static_pages#home"
  get "/apropos", to: "static_pages#apropos"
  get "/formation", to:  "static_pages#formation"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  def apropos

  end
  def formation

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
     <div class="container">
       <!-- Brand and toggle get grouped for better mobile display -->
       <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
         <%= link_to "Dev Update", root_path,class: "navbar-brand" %>
       </div>

       <!-- Collect the nav links, forms, and other content for toggling -->
       <div class="collapse navbar-collapse" id="navbar-collapse-1">
         <ul class="nav navbar-nav navbar-right">
           <li><%= link_to "Formation", formation_path %></li>
            <li><a href="#"></a></li>
           <li><a href="#">A propos</a></li>
           <li><%= button_to "S'inscrivez-vous", root_path, class: "btn btn-default btn-lg"  %></li>

         </ul>

       </div><!-- /.navbar-collapse -->
     </div><!-- /.container -->
   </nav><!-- /.navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Devupdate</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
   <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track'=> true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>

  <body>

    <div class="container">
      <%= render 'layouts/navbar' %>
      
      <%= yield %>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
   <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="row" id="home">
  <div class="col-md-5" id="content-pvaleur">
    <h1 class="pvaleur">Complétez vos compétences techs</h1>
    <h4 class="baseline">Dev Update vous permet de trouver le développeur idéal pour
       appronfondir vos connaissances technologiques plus rapidement,
       par des séances de monitoring et de code en live.
    </h4>
       <%= button_to "Inscrivez-vous, c'est gratuit !", root_path, class: "btn btn-danger btn-lg"  %>
  </div>
  <div class="col-md-6 hidden-xs ">
    <img src="/coding_photo.jpg" alt="" class="img-responsive"style="width:100%; min-height:380px!important">
  </div>
</div>

<div class="container marketing">
    <div class="row">
      <div class="text-center">
        <h2 class="title1">Nous sommes fais pour ceux qui savent déjà coder</h2>
      </div>
      <div class="col-lg-4">
        <div class="text-center">
          <img src="/code.png" alt="">
        </div>
        <h2 class="qualité"> Pré-requis, avoir de bonnes bases dans un langage informatique </h2>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <div class="text-center">
          <img src="/support.png" alt="">
        </div>
        <h2 class="qualité">Nos profs sont des développeurs senoirs formés chez Epitech ou travaillant dans des startups comme Github; </h2>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <div class="text-center">
          <img src="/clock.png" alt="">
        </div>
        <h2 class="qualité">La formation est de 5 heures/semaine pendant 1 mois  </h2>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->
</div>